server:
  master:
    port: 8080
  agent:
    port: 8081
  servlet:
    session:
      timeout: 1800

mapper:
  identity: MYSQL
  mappers: com.sugon.gsq.om.db.util.MyMapper
  not-empty: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sugon.gsq.om.db.entity

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true

spring:
  application:
    name: operation-manager
  freemarker:
    cache: false
    request-context-attribute: request
  jackson:
    time-zone: GMT+8
  output:
    ansi:
      enabled: DETECT

  datasource:
    url: jdbc:mysql://slave01:3306/operation_manager?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Admin1234@sugon
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      test-on-borrow: true

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  swagger:
    enabled: true
    title: OM应用自动化部署系统
    description: 接口API调试专用
    version: RELEASE-4.0.5
#    base-package: com.sugon.gsq.om.controller
    contact:
      name: gaoshq
      email: gaoshq@sugon.com
      url: http://sugon.com
    security:
      filter-plugin: false
      username: admin
      password: admin

logging:
  level:
    com.sugon.gsq.om.db.mapper: INFO
    root: info
    tk:
      mybatis:
        springboot:
          mapper: INFO